spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host:
    port:
    username:
    password:
    protocol: smtp
  profiles:
    active:
    - dev
    #include:
     # others application-{name}.yml properties to add
app:
  title: My Spring Application with system properties
